### ISSUE TITLE
Binary Publish Component presentation

### ISSUE THREAD

**Issue by sshibani** [dd4t/DD4T.TridionTemplates#24] opened 2016-09-07 15:51 UTC
Dynamic ComponentPresentation TBB does not implement the logic to publish Binaries like Dynamic Page

**Comment by quirijnslings** [comment] 2017-03-30 16:48
Is this really a bug, @sshibani? I see that multimedia components do get published. The logic is in a different location. For components, it is triggered from the ComponentBuilder, while for pages it is triggered from the Generate Dynamic Page template. But in both cases, binaries are published. 
It may be inconsistent but it is working.

**Comment by quirijnslings** [comment] 2018-02-09 09:40
This is not a bug (see previous comment), we won't fix.

**Closed as completed by quirijnslings** 2018-02-09 09:40 UTC
Labels: bug, wontfix
